guest1 = Guest.create(first_name: "guestfirstname1", last_name: "guestlastname1", phone_number: 1111111111, email_address: "guestemail1@email.com", address: "guestaddress1")
guest2 = Guest.create(first_name: "guestfirstname2", last_name: "guestlastname2", phone_number: 2222222222, email_address: "guestemail2@email.com", address: "guestaddress2")
guest3 = Guest.create(first_name: "guestfirstname3", last_name: "guestlastname3", phone_number: 3333333333, email_address: "guestemail3@email.com", address: "guestaddress3")
guest4 = Guest.create(first_name: "guestfirstname4", last_name: "guestlastname4", phone_number: 4444444444, email_address: "guestemail4@email.com", address: "guestaddress4")
guest5 = Guest.create(first_name: "guestfirstname5", last_name: "guestlastname5", phone_number: 5555555555, email_address: "guestemail5@email.com", address: "guestaddress5")
guest6 = Guest.create(first_name: "guestfirstname6", last_name: "guestlastname6", phone_number: 6666666666, email_address: "guestemail6@email.com", address: "guestaddress6")
guest7 = Guest.create(first_name: "guestfirstname7", last_name: "guestlastname7", phone_number: 7777777777, email_address: "guestemail7@email.com", address: "guestaddress7")
guest8 = Guest.create(first_name: "guestfirstname8", last_name: "guestlastname8", phone_number: 8888888888, email_address: "guestemail8@email.com", address: "guestaddress8")
guest9 = Guest.create(first_name: "guestfirstname9", last_name: "guestlastname9", phone_number: 9999999999, email_address: "guestemail9@email.com", address: "guestaddress9")
guest10 = Guest.create(first_name: "guestfirstname10", last_name: "guestlastname10", phone_number: 9999999999, email_address: "guestemail10@email.com", address: "guestaddress10")

host1 = Host.create(first_name: "hostfirstname1", last_name: "hostlastname1", phone_number: 3333333333, email_address: "hostemail1@email.com", address: "hostaddress1")
host2 = Host.create(first_name: "hostfirstname2", last_name: "hostlastname2", phone_number: 4444444444, email_address: "hostemail2@email.com", address: "hostaddress2")
host3 = Host.create(first_name: "hostfirstname3", last_name: "hostlastname3", phone_number: 5555555555, email_address: "hostemail3@email.com", address: "hostaddress3")
host4 = Host.create(first_name: "hostfirstname4", last_name: "hostlastname4", phone_number: 3333733333, email_address: "hostemail4@email.com", address: "hostaddress4")
host5 = Host.create(first_name: "hostfirstname5", last_name: "hostlastname5", phone_number: 4447444444, email_address: "hostemail5@email.com", address: "hostaddress5")
host6 = Host.create(first_name: "hostfirstname6", last_name: "hostlastname6", phone_number: 5557555555, email_address: "hostemail6@email.com", address: "hostaddress6")
host7 = Host.create(first_name: "hostfirstname7", last_name: "hostlastname7", phone_number: 3333773333, email_address: "hostemail7@email.com", address: "hostaddress7")
host8 = Host.create(first_name: "hostfirstname8", last_name: "hostlastname8", phone_number: 4474444444, email_address: "hostemail8@email.com", address: "hostaddress8")
host9 = Host.create(first_name: "hostfirstname9", last_name: "hostlastname9", phone_number: 5555557559, email_address: "hostemail9@email.com", address: "hostaddress9")
host10 = Host.create(first_name: "hostfirstname10", last_name: "hostlastname10", phone_number: 3373333330, email_address: "hostemail10email.com", address: "hostaddress10")

house1 = House.create(address: "1600 Pennsylvania Avenue NW, Washington, DC 20500 ", bedrooms:30, bathrooms: 45, parking: 200, guest_limit: 300, pet_friendly:true, house_type: "House", cost_per_day: 500, host_id: 1, img_url: "https://cdn.rttnews.com/articleimages/ustopstories/2017/february/trump-whitehouse-020817-lt.jpg")
house2 = House.create(address: "4 Privet Dr, Bracknell, Berkshire", bedrooms: 2, bathrooms: 2, parking: 3, guest_limit: 6, pet_friendly:false, house_type: "Townhouse", cost_per_day: 100, host_id: 2, img_url: "https://images.immediate.co.uk/production/volatile/sites/3/2016/09/118078.jpg")
house3 = House.create(address: "12 Bywater Way, Hobbiton, The Shire", bedrooms: 1, bathrooms: 1, parking: 0, guest_limit: 5, pet_friendly:true, house_type: "House", cost_per_day: 200, host_id: 3, img_url: "https://mk0caropela3e0g49gxg.kinstacdn.com/wp-content/uploads/2018/10/15189132237_1329230396_z.jpg")
house4 = House.create(address: "16 Fire Lane, Seattle, Washington", bedrooms: 1, bathrooms: 0, parking: 2, guest_limit: 1, pet_friendly:false, house_type: "House", cost_per_day: 7, host_id: 4, img_url: "https://images.indianexpress.com/2018/10/house-on-fire_1200_getty.jpg")
house5 = House.create(address: "1835 73rd Ave NE, Medina, WA 98039", bedrooms: 6, bathrooms: 5, parking: 8, guest_limit: 40, pet_friendly:true, house_type: "House", cost_per_day: 400, host_id: 5, img_url: "https://moneydotcomvip.files.wordpress.com/2018/01/180117-bill-gates-bill-gates-estate.jpg")
house6 = House.create(address: "217 E Broadway, New York, NY 10002", bedrooms: 0, bathrooms: 1, parking: 0, guest_limit:7, pet_friendly:true, house_type: "Apartment", cost_per_day: 60, host_id: 6, img_url: "https://pbs.twimg.com/media/CN69anpWEAAyZ_-.png")
house7 = House.create(address: "124 Conch Street, Bikini Bottom, Pacific Ocean", bedrooms: 1, bathrooms: 1, parking: 1, guest_limit: 4, pet_friendly:true, house_type: "Fruit", cost_per_day: 35, host_id: 7, img_url: "https://vignette.wikia.nocookie.net/spongebob/images/f/fb/Pineapple.png/revision/latest?cb=20190614224253")
house8 = House.create(address: "6 Swamp Place, Dagobah, Dagobah System, Sluis Sector, Outer Rim Territories", bedrooms: 1, bathrooms: 0, parking: 1, guest_limit: 2, pet_friendly:true, house_type: "House", cost_per_day: 8, host_id: 8, img_url: "https://i.pinimg.com/originals/44/14/bc/4414bcf8452262ce0440d3158b30e620.jpg")
house9 = House.create(address: "1 Island Dr, Southeast Island Area", bedrooms: 2, bathrooms: 1, parking: 1, guest_limit: 6, pet_friendly:true, house_type: "House", cost_per_day: 90, host_id: 9, img_url: "https://vignette.wikia.nocookie.net/dragonuniverse/images/a/ab/Kame_House.png/revision/latest?cb=20170424114929")
house10 = House.create(address: "Red Keep, King's Landing, The Crownlands", bedrooms: 50, bathrooms: 9, parking: 9, guest_limit: 800, pet_friendly:false, house_type: "Castle", cost_per_day: 500, host_id: 10, img_url: "https://wikiofthrones.com/static/uploads/2018/04/red-keep-compressed.jpg")

reservation1 = Reservation.create(number_of_guests: 1, reservation_start_date: "01-01-2020", reservation_end_date: "01-02-2020", guest_id:1, house_id:1)
reservation2 = Reservation.create(number_of_guests: 2, reservation_start_date: "02-01-2020", reservation_end_date: "02-02-2020", guest_id:2, house_id:2)
reservation3 = Reservation.create(number_of_guests: 5, reservation_start_date: "03-01-2020", reservation_end_date: "03-02-2020", guest_id:3, house_id:3)
reservation4 = Reservation.create(number_of_guests: 4, reservation_start_date: "04-01-2020", reservation_end_date: "05-19-2020", guest_id:4, house_id:4)
reservation5 = Reservation.create(number_of_guests: 3, reservation_start_date: "05-01-2020", reservation_end_date: "05-02-2020", guest_id:5, house_id:5)
reservation6 = Reservation.create(number_of_guests: 2, reservation_start_date: "06-01-2020", reservation_end_date: "06-02-2020", guest_id:6, house_id:6)
reservation7 = Reservation.create(number_of_guests: 3, reservation_start_date: "07-01-2020", reservation_end_date: "07-02-2020", guest_id:7, house_id:7)
reservation8 = Reservation.create(number_of_guests: 2, reservation_start_date: "08-01-2020", reservation_end_date: "08-02-2020", guest_id:8, house_id:8)
reservation9 = Reservation.create(number_of_guests: 3, reservation_start_date: "09-01-2020", reservation_end_date: "09-02-2020", guest_id:9, house_id:9)
reservation10 = Reservation.create(number_of_guests: 6, reservation_start_date: "10-01-2020", reservation_end_date: "10-02-2020", guest_id:10, house_id:10)

review1 = Review.create(rating: 5, comment: "comment1", guest_id:1, reservation_id: 1)
review2 = Review.create(rating: 2, comment: "comment2", guest_id:2, reservation_id: 2)
review3 = Review.create(rating: 5, comment: "comment3", guest_id:3, reservation_id: 3)
review4 = Review.create(rating: 2, comment: "comment4", guest_id:4, reservation_id: 4)
review5 = Review.create(rating: 5, comment: "comment5", guest_id:5, reservation_id: 5)
review6 = Review.create(rating: 2, comment: "comment6", guest_id:6, reservation_id: 6)
review7 = Review.create(rating: 5, comment: "comment7", guest_id:7, reservation_id: 7)
review8 = Review.create(rating: 2, comment: "comment8", guest_id:8, reservation_id: 8)
review9 = Review.create(rating: 5, comment: "comment9", guest_id:9, reservation_id: 9)
review10 = Review.create(rating: 2, comment: "comment10", guest_id:10, reservation_id: 10)